--- 
pid: tmp/pids/thin.pid
address: 0.0.0.0
wait: 30
port: 9600
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/github/shanshui18
